### ISSUE TITLE
gdb can't connect to a device

### ISSUE THREAD

**Issue by sheinz** [resetnow/esp-gdbstub#2]
It seems like I did everything correct to include gdb-stub into the project. But, I can't connect to a device with gdb :(
```
xtensa-lx106-elf-gdb -b 115200
GNU gdb (crosstool-NG 1.20.0) 7.5.1
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_unknown-linux-gnu --target=xtensa-lx106-elf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) set remotelogfile gdb.log
(gdb) file ./build/http_get.out 
Reading symbols from /home/yura/esp/esp-open-rtos/examples/http_get/build/http_get.out...done.
(gdb) target remote /dev/ttyUSB0
Remote debugging using /dev/ttyUSB0
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
```
gdb.log:
```
cat gdb.log 

w +$qSupported:multiprocess+;qRelocInsn+#2a
r <Timeout: 2 seconds>
w $qSupported:multiprocess+;qRelocInsn+#2a
r <Timeout: 2 seconds>
w $qSupported:multiprocess+;qRelocInsn+#2a
r <Timeout: 2 seconds>
w $qSupported:multiprocess+;qRelocInsn+#2a
r <Timeout: 2 seconds><Timeout: 2 seconds>
w -
r <Timeout: 2 seconds>
w -
r <Timeout: 2 seconds>
w -+$Hg0#df
r <Timeout: 2 seconds>
w $Hg0#df
r <Timeout: 2 seconds>
w $Hg0#df
r <Timeout: 2 seconds>
w $Hg0#df
r <Timeout: 2 seconds><Timeout: 2 seconds>
w -
r <Timeout: 2 seconds>
w -
r <Timeout: 2 seconds>
w -+$?#3f
r <Timeout: 2 seconds>
w $?#3f
r <Timeout: 2 seconds>
w $?#3f
r <Timeout: 2 seconds>
w $?#3f
r <Timeout: 2 seconds><Timeout: 2 seconds>
```

Btw, esptool gives warning:
```
esptool.py v1.3-dev
Warning: ELF binary has undefined symbol gdbstub_init_debug_entry
```

**Comment by vlad-ivanov-name** [comment]
Since nothing comes out of the device, I would expect something major broke. I didn't check if it works after the FreeRTOS upgrade. I don't have a lot of time on my hands right now but I'll look into it at the weekend. 

You could also try placing `gdbstub_do_break()` after `gdbstub_init()` in your code. Checking serial speed in both device <s>and GDB</s> could be helpful too.

**Comment by sheinz** [comment]
Hi @resetnow,

I tried reverting *eor* till your initial support of esp-gdbstub. And I still can't get gdb to connect to the device. But the device seems to work. And if I place a breakpoint with `gdbstub_do_break()` I receive from the terminal:
```
$T05#b9
```
Also if I hit Ctrl-C in the terminal with running firmware I also seems to get device to stop:
```
$T02#b6
```

**Comment by vlad-ivanov-name** [comment]
>`$T05#b9`
>`$T02#b6`

These are correct stop reasons and GDB should handle them. Another issue I had: debugging didn't work when both GDB and a serial port client were connected to same serial port.

**Comment by sheinz** [comment]
I don't know why but in OSX gdb can't connect to the device.
In Linux everything works fine.

**Comment by vlad-ivanov-name** [comment]
I'll close it since it seems to be an OSX-specific problem of GDB.
