### ISSUE TITLE
Error linking libraries

### ISSUE THREAD

**Issue by CorrederaJorge** [resetnow/esp-gdbstub#3]
Hi:
Thank you very much for your effort creating this tool make debug in the esp. I am trying to make a simple example to create a tutorial to set up the framework with freeRtos. I am trying to add this tool in the blink demo from [https://github.com/SuperHouse/esp-open-rtos](url). I am using Linux Mint and I have compiled esp open rtos and blinky example is working WITHOUT debug mode.

In order to add debug mode I have installed premake5 and I have typed:
```
premake5 gmake --with-eor=/home/workspace/esp-open-rtos --with-threads
```
After that it generated make file. 

I have copied the project folder "esp-gdbstub" inside "esp-open-rtos" folder. I have modified Makefile from blink project to look like:

```
PROGRAM=blink

EXTRA_CFLAGS+=-I../../esp-gdbstub/include
EXTRA_LDFLAGS+=-L../../esp-gdbstub/lib

include ../../common.mk

LIBS+=esp-gdbstub
```

I am not sure where to add:
`CFLAGS+=-DportREMOVE_STATIC_QUALIFIER -DINCLUDE_pcTaskGetTaskName=1` . So I have compiled without it. 

I have modified blinky project blink.c

```
/* The classic "blink" example
 *
 * This sample code is in the public domain.
 */
#include <stdlib.h>
#include "espressif/esp_common.h"
#include "esp/uart.h"
#include "FreeRTOS.h"
#include "task.h"
#include "esp8266.h"

#include "gdbstub.h"
const int gpio = 2;

[..]
void user_init(void)
{
    uart_set_baud(0, 115200);
    gdbstub_init();

    xTaskCreate(blinkenTask, "blinkenTask", 256, NULL, 2, NULL);
    //xTaskCreate(blinkenRegisterTask, "blinkenRegisterTask", 256, NULL, 2, NULL);
}
```

When I compile I see an error linking libraries.

```
LD build/blink.out
../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x24): undefined reference to `pxReadyTasksLists'
../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x28): undefined reference to `pxReadyTasksLists'
../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x2c): undefined reference to `pxDelayedTaskList'
../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x30): undefined reference to `pxOverflowDelayedTaskList'
../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x34): undefined reference to `xTasksWaitingTermination'
../../esp-gdbstub/lib/libesp-gdbstub.a(gdbstub-freertos.o):(.literal+0x38): undefined reference to `xSuspendedTaskList'
collect2: error: ld returned 1 exit status
../../common.mk:212: recipe for target 'build/blink.out' failed
make: *** [build/blink.out] Error 1
```

Thank you very much for your time. What am I doing wrong?

**Comment by vlad-ivanov-name** [comment]
>I am not sure where to add

Hi, you can add it to EXTRA_CFLAGS. Make sure to `make clean` after.

Note that GDB will likely crash shortly after you see a list of threads. You can configure without thread option for a more reliable debugging (but there have been reports it still crashes in some cases, I'm currently investigating this).

**Comment by CorrederaJorge** [comment]
Hi,
I have created a tutorial how to use the tool you have created. [Tutorial](http://correderajorge.github.io/esp-gdb-freertos/)

Thank you very much.

**Comment by vlad-ivanov-name** [comment]
Did features like line-stepping and such work for you?

**Comment by CorrederaJorge** [comment]
No, it just stop in the line using ram breakpoint or hardware breakpoint.

When I try line stepping It crash and I see:

```
Program received signal SIGTRAP, Trace/breakpoint trap.
blinkenTask (pvParameters=<optimized out>) at /home/workspace/esp-open-rtos/examples/blink/blink.c:23
23	        gdbstub_do_break();
/opt/esp-open-sdk/crosstool-NG/.build/src/gdb-7.10/gdb/inline-frame.c:171: internal-error: inline_frame_this_id: Assertion `!frame_id_eq (*this_id, outer_frame_id)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? 
This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.
(y or n) [answered Y; input not from terminal]
/opt/esp-open-sdk/crosstool-NG/.build/src/gdb-7.10/gdb/inline-frame.c:171: internal-error: inline_frame_this_id: Assertion `!frame_id_eq (*this_id, outer_frame_id)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) [answered Y; input not from terminal]
```

**Comment by vlad-ivanov-name** [comment]
Thanks for this, I have heard other people having problems like you described, I'll look into it.

**Comment by CorrederaJorge** [comment]
Let me know if you need more feedback. Awesome support. Thank you very much.

**Comment by vlad-ivanov-name** [comment]
@CorrederaJorge I have reproduced the crash and updated README.md with a solution. Basically, you need to turn optimization off for your main program file with `PROGRAM_CFLAGS+=-O0`. This way, line stepping will work.
