### ISSUE TITLE
Compile & configuration

### ISSUE THREAD

**Issue by marrog86** [resetnow/esp-gdbstub#7]
Hello, i want to try bdbstub for esp8266 on Linux. 

i made steps like described on Github, stipping with following error: 

```
LD build/pwm.elf
/home/martin/workspace/esp8266_pwm/build/main/libmain.a(pwm_example_main.o):(.literal.app_main+0x18): undefined reference to `gdbstub_init'
/home/martin/workspace/esp8266_pwm/build/main/libmain.a(pwm_example_main.o): In function `app_main':
/home/martin/workspace/esp8266_pwm/main/pwm_example_main.c:61: undefined reference to `gdbstub_init'
collect2: error: ld returned 1 exit status
/home/martin/esp/ESP8266_RTOS_SDK/make/project.mk:509: die Regel für Ziel „/home/martin/workspace/esp8266_pwm/build/pwm.elf“ scheiterte
make: *** [/home/martin/workspace/esp8266_pwm/build/pwm.elf] Fehler 1
```

so i tried the steps in http://correderajorge.github.io/esp-gdb-freertos/ , downloading premake5 and executing says: 

```
~/esp$ ./premake5 gmake --with-eor=/home/martin/esp/esp-open-rtos/
Error: invalid option 'with-eor'
```

how to make this working?

**Comment by vlad-ivanov-name** [comment]
Hi, it has been a while since I developed this project. I don't have the hardware right now, but I will test the build in the next few days.

**Comment by vlad-ivanov-name** [comment]
Hi again, so about this:

```
~/esp$ ./premake5 gmake --with-eor=/home/martin/esp/esp-open-rtos/
```

For me this shows no errors. I'm using premake5 built from commit https://github.com/premake/premake-core/commit/09ee8334933e3953d96070047512820730518cc1

The rest I will try to fix

**Comment by vlad-ivanov-name** [comment]
@marrog86 I was able to build gdbstub with recent esp-open-rtos as described in this repo. Looking at your build log, you might have forgotten to add 

```
LIBS+=esp-gdbstub
```

Hence the undefined symbols. Feel free to reopen if this doesn't fix the issue.
